### ISSUE TITLE
env中变量名称错误

### ISSUE THREAD

**Issue by hshx123** [y-young/nazurin#107]
问题点：https://github.com/y-young/nazurin/blob/cb090063eacf1b83b675e456caa0e6c264b18d1c/.env.example#L52

依据 [nazurin/middleware.py](https://github.com/y-young/nazurin/blob/master/nazurin/middleware.py) ，
“Telegram 群组 ID，以英文逗号分隔。这些群组中的用户能够在群聊中使用机器人”该变量名应是 **ALLOW_GROUP** ，env文件和配置文档中均是 GROUP_ID

**Comment by y-young** [comment]
Thanks for your report
