### ISSUE TITLE
Heroku 部署失敗

### ISSUE THREAD

**Issue by eyjge** [y-young/nazurin#18]
嘗試了很多次，都是失敗，之前是寫unsupported port:27017 [Error:111],現在是寫unsupported start tag "topologydescription" at byte offset 92[acgimage-logs-1621602554456.txt](https://drive.google.com/file/d/1K6oYd6Ww43i6WiC3wMf0DuGYqa3gli2k/view?usp=drivesdk)

**Comment by y-young** [comment]
你提供的日志不完整，无法判断具体原因，但看上去已经部署成功了，这个问题是始终存在的，还是特定命令才能触发？
可以停留在日志页面然后再尝试复现这个问题，这样可以获取到完整的日志，如果可以的话请顺便提供触发此问题的命令

**Comment by eyjge** [comment]
那這個呢？https://drive.google.com/file/d/1K7CjnRSt8CtvHUln-penx9IEL5_8ltkh/view?usp=drivesdk

**Comment by y-young** [comment]
嗯大概了解了，你应该是在配置中指定了使用本地的MongoDB数据库，但是Heroku上没有，所以无法连接到27017端口，建议考虑换一个数据库，比如Firebase，或者到MongoDB Atlas上申请一个免费的远程数据库

**Comment by eyjge** [comment]
好的謝謝,但是用MongoDB Atlas 要寫哪個端口？

**Comment by y-young** [comment]
> 好的謝謝,但是用MongoDB Atlas 要寫哪個端口？

MongoDB Atlas会给你一个类似`mongodb://username:password@localhost:27017`的连接地址，按照那个填就行了

**Comment by eyjge** [comment]
請問是在哪裏可以找到？

**Comment by y-young** [comment]
> 請問是在哪裏可以找到？

你需要先创建一个数据库用户，记下用户名和密码，然后到Clusters页面点击Connect按钮，选择"Connect your application"，弹出的对话框中会有一个连接地址，将其中的用户名、密码和数据库名称替换即可，具体可参考对话框中的说明

**Comment by eyjge** [comment]
現在可以存入數據庫了,但是無法把相片發到頻道,aiogram.utils.exceptions.ChatNotFound: Chat not found

**Comment by eyjge** [comment]
https://drive.google.com/file/d/1L15nDqCX6rCv2CyhN1xQSCNa8q_EC_bg/view?usp=drivesdk

**Comment by y-young** [comment]
> 現在可以存入數據庫了,但是無法把相片發到頻道,aiogram.utils.exceptions.ChatNotFound: Chat not found

如果确定`GALLERY_ID`和`ALBUM_ID`正确的话，检查一下有没有将bot设置为频道管理员

PS: 密钥是类似`/123456:abcdefg`的那一串

**Comment by eyjge** [comment]
好的謝謝,另外我發現我原來忘記把新做的bot加進頻道了....

**Comment by y-young** [comment]
> 好的謝謝他正常了,另外我發現我原來忘記把新做的bot加進頻道了....

觉得好用的话就点个star吧 :D

**Comment by y-young** [comment]
> 好的謝謝他正常了,另外我發現我原來忘記把新做的bot加進頻道了....

觉得好用的话就点个star吧 :D

**Comment by eyjge** [comment]
> > 好的謝謝他正常了,另外我發現我原來忘記把新做的bot加進頻道了....
> 
> 觉得好用的话就点个star吧 :D

點了( ╹▽╹ )
