### ISSUE TITLE
Forward all pictures in the picture group to the telegram gallery channel

### ISSUE THREAD

**Issue by Misaka13514** [y-young/nazurin#20]
**Is your feature request related to a problem? Please describe.**

Sometimes multiple pictures from the same link are combined and sent as a group, and the bot will only forward one picture to the gallery channel.

**Describe the solution you'd like**

Forward all pictures in the picture group to the telegram gallery channel

**Describe alternatives you've considered**

Now I can only manually copy the link of the picture group (from other channel) and send it to the bot.

**Additional context**

I don't know if this can be done. 😓

**Comment by y-young** [comment]
Thanks for reporting.
In fact that's a known issue, due to the limitations of Telegram API, this cannot be implemented easily, and is therefore postponed. We'll reinvestigate this issue in the future, sorry for the current inconvience.
Also, contributions are welcomed if you find a solution later.

**Comment by Misaka13514** [comment]
A useless suggestion: add an option to not forward the message, only process the link. (like only a single link)
To be honest, the format sent by this robot is not worse than the source of the forwarding.

**Comment by y-young** [comment]
> A useless suggestion: add an option to not forward the message, only process the link. (like only a single link)
> To be honest, the format sent by this robot is not worse than the source of the forwarding.

Introduced a new strategy to disable forwarding if there're multiple images, please have a try.

**Comment by Misaka13514** [comment]
> Introduced a new strategy to disable forwarding if there're multiple images, please have a try.

Wow! thank you

**Comment by y-young** [comment]
Fixed.
