### ISSUE TITLE
更新最新的dev-v2报错

### ISSUE THREAD

**Issue by bottomash** [y-young/nazurin#30]
![image](https://user-images.githubusercontent.com/48351249/141306901-06034301-17be-424a-a220-a4687911f9f4.png)

出现上图的报错，回退master分支就不报错了。

**Comment by y-young** [comment]
dev-v2的代码之前已经合入master分支，最新的代码在master分支

**Comment by bottomash** [comment]
好的，感谢大佬。master分支也支持微博了，感谢。
