### ISSUE TITLE
群组内识别另外的机器人（例如ifttt）的链接。

### ISSUE THREAD

**Issue by bottomash** [y-young/nazurin#32]
已经设置ifttt的id为 allow_id，但是对ifttt发在群组里的链接没反应。对我自己发的链接能够正常触发。
设定是只对群组内非机器人用户的链接识别，还是一个bug或技术性难题？
如果能够识别其他机器人的链接，收藏图片就能全自动了。

**Comment by y-young** [comment]
我记得Telegram有限制bot直接不能互相触发：https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

**Comment by bottomash** [comment]
好的，感谢回复。
