### ISSUE TITLE
能不能添加Wallhaven的支持

### ISSUE THREAD

**Issue by love2wind** [y-young/nazurin#33]
看到这个机器人不错，但是没有上传网盘的功能，大佬能不能整合一下这个。
https://github.com/Yash-Garg/node-wallhaven-bot

**Comment by y-young** [comment]
你是希望支持收藏WallHaven的图片是吗？

**Comment by love2wind** [comment]
> 你是希望支持收藏WallHaven的图片是吗？

我是想要能够下载Wallhaven的图片到网盘，目前我的方案是先用https://github.com/Yash-Garg/node-wallhaven-bot这个机器人下载到TG，然后再发送给nazurin上传到网盘

**Comment by y-young** [comment]
也就是说希望能识别WallHaven的链接，然后自动下载并保存是吧？(我一般把这个过程称为收藏)

**Comment by love2wind** [comment]
> 也就是说希望能识别WallHaven的链接，然后自动下载并保存是吧？(我一般把这个过程称为收藏)

是的，是的

**Comment by love2wind** [comment]
还有能不能加上bing Wallpaper每日自动推送收藏吗？
这里有个项目https://github.com/miaotony/BingImages

**Comment by y-young** [comment]
> 还有能不能加上bing Wallpaper每日自动推送收藏吗？ 这里有个项目https://github.com/miaotony/BingImages

自动爬取目前不在考虑范围内，只支持用户手动触发；另外，如果是不同的功能请开一个新Issue。
