### ISSUE TITLE
ffmpeg转换的Gif.mp4无法在安卓设备里播放

### ISSUE THREAD

**Issue by ArimuraRomi** [y-young/nazurin#34]
**Describe the bug**
![image](https://s2.loli.net/2021/12/28/P7NChBsYIr9tfkp.jpg)
列：https://t.me/NazurinDemoTestChannel/1107
使用默认 `ffmpeg -i "{config.path}" -vcodec libx264 -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -y "{output.path}" ` 参数转换
在安卓设备（安卓8 & 10）里无法播放，显示为白屏
在IOS、PC端和Web端（& Web在线url预览）里正常

**To Reproduce**
1. /pixiv 93435263
2. https://t.me/NazurinDemoTestChannel/1107

**Expected behavior**
我直接用另外一个同类项目 [my-telegram-bots/Pixiv_bot](https://github.com/my-telegram-bots/Pixiv_bot) 里 https://github.com/my-telegram-bots/Pixiv_bot/blob/50a14ce58bdb12b125c8668cf78e988b714601d3/handlers/pixiv/tools.js#L162 的 ffmpeg 参数更改来使用
`ffmpeg -i "{config.path}" -vcodec libx264 -vf "format=yuv420p,scale=trunc(iw/2)*2:trunc(ih/2)*2" -y "{output.path}" `
结果：https://t.me/NazurinDemoTestChannel/1110
测试结果：安卓、IOS、PC端和Web端均正常显示

![image](https://s2.loli.net/2021/12/28/cESlGMvWKTYxPyn.png)
但Web在线url预览不行

此外该项目还额外使用 mp4fpsmod 添加 fps metadata ，而我还没添加过，可能是这个问题

**Error output / Logs**
无

**Environment (please complete the following information):**
 - OS: Heroku

**Additional context**
无

**Comment by y-young** [comment]
现在应该修复了，如果网页端提示不支持也有可能是Telegram服务器的问题，刷新一下应该就好了

**Comment by ArimuraRomi** [comment]
> 現在應該修復了，如果網頁端提示不支持也有可能是 Telegram 服務器的問題，刷新一下應該就好了

感谢作者，辛苦了
