### ISSUE TITLE
onedrive 配置出现Error: 'access_token'

### ISSUE THREAD

**Issue by bottomash** [y-young/nazurin#35]
添加OneDrive作为存储，配置`OD_SECRET` `OD_RF_TOKEN` `OD_CLIENT`，没有配置access token。
我在Wiki里并没有看到`access token` 如何设置，请问如何配置access_token？
![image](https://user-images.githubusercontent.com/48351249/147570111-c57fbfc9-9638-414a-bcfd-43d24f39d6af.png)

**Comment by y-young** [comment]
这里是认证的返回结果中没有`access_token`，可能是认证失败，请检查 API 凭据是否有误

**Comment by bottomash** [comment]
![image](https://user-images.githubusercontent.com/48351249/160060972-69cad058-c7bf-4888-9e17-d22f38f43526.png)
api 权限已经授予，且获得了refresh token。多次尝试依然跟开头的错误一样，请问还需要什么以便于解决问题？

**Comment by y-young** [comment]
我更新了一下，请使用最新代码重新操作，应该能在日志中看到详细的错误信息

**Comment by bottomash** [comment]
[In reply to bottomash]
OneDrive authorization error: AADSTS50034: The user account a216bfd9-8b0d-442b-8e37-4d3bc3ba5981 does not exist in the 5f9243d4-afe2-46c4-ae37-819d72787ad7 directory. To sign into this application, the account must be added to the directory.
Trace ID: eb07cd9b-53b1-4505-a0ce-b9fc1514ed00
Correlation ID: f8439cc2-5dd4-45f4-ac0e-c0de1979b1c1
Timestamp: 2022-03-25 07:23:57Z

**Comment by bottomash** [comment]
nazurin - ERROR - {'error': 'invalid_grant', 'error_description': 'AADSTS50034: The user account a216bfd9-8b0d-442b-8e37-4d3bc3ba5981 does not exist in the 5f9243d4-afe2-46c4-ae37-819d72787ad7 directory. To sign into this application, the account must be added to the directory.\r\nTrace ID: a8977ba2-d77c-4f6b-9214-0e91dd65f301\r\nCorrelation ID: 71056b55-1579-4944-a488-73da63a67729\r\nTimestamp: 2022-03-25 08:19:25Z', 'error_codes': [50034], 'timestamp': '2022-03-25 08:19:25Z', 'trace_id': 'a8977ba2-d77c-4f6b-9214-0e91dd65f301', 'correlation_id': '71056b55-1579-4944-a488-73da63a67729', 'error_uri': 'https://login.microsoftonline.com/error?code=50034'}

**Comment by y-young** [comment]
我无法确定具体原因，不过你可以参考下面两个教程再检查一下，注意“受支持的帐户类型”，“应用程序(客户端) ID”和“客户端密码”是否正确
https://rclone.org/onedrive/#getting-your-own-client-id-and-key
https://ovi.swo.moe/zh/docs/advanced#%E4%BD%BF%E7%94%A8%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84-client-id-%E4%B8%8E-secret

**Comment by bottomash** [comment]
搞不明白了，算了。OneDrive就算了吧。不过有考虑Google Photo做新的存储位置吗？非常感谢你的帮助！

**Comment by y-young** [comment]
> 有考虑Google Photo做新的存储位置吗？
没有，但现在支持Google Drive。Google Photos有什么优势吗？貌似存储空间是一起算的

**Comment by bottomash** [comment]
> > 有考虑Google Photo做新的存储位置吗？
> > 没有，但现在支持Google Drive。Google Photos有什么优势吗？貌似存储空间是一起算的

存储空间是一起算的，但是Google photo和Google drive是隔离的，两者的内容不会同步。
Google photo的优势在于移动端设备使用方便，管理照片方便。其实还是我喜欢(❤ ω ❤)Google photo管理照片，所以就问问能不能支持Google photo。非常感谢回复。

**Comment by y-young** [comment]
> 存储空间是一起算的，但是Google photo和Google drive是隔离的，两者的内容不会同步。

看了下网页版貌似支持从Drive上传，或许可以凑合一下。

> Google photo的优势在于移动端设备使用方便，管理照片方便。

确实现在对图片的浏览和管理并没有一个好的方案，Telegram的Channel配合标签可以勉强用，但是复杂的筛选就做不到了；我有在考虑开发一套专用的App，毕竟Google Photos不支持标签等特定功能，但短期内肯定是做不出来的。

**Comment by bottomash** [comment]
好的，非常感谢。
