### ISSUE TITLE
存储时根据来源用文件夹进行分类

### ISSUE THREAD

**Issue by Theergold** [y-young/nazurin#40]
希望在储存文件夹里面再通过图片的来源分在不同文件夹里面,这样能稍微方便一点找图

**Comment by y-young** [comment]
这个已在考虑中，还有考虑根据画师进一步分类，但问题是不便于顺序浏览
如果有具体的需求可以说明一下以供参考

**Comment by yotv2000tw** [comment]
Pixiv自選參數進行資料夾分類呢？譬如可以自選分類（漫畫／插圖／動圖）、作品資料（作品名稱、作品ID、作者ID、上傳時間、首標籤、頁數等），然後自己看怎麼分類
Twitter的話可能就只能透過用戶ID之類的，其他部分不太有研究
譬如我能自己選擇用 `Pixiv/Manga(參數調整)/PIXIV_ID(參數調整)` 儲存，檔名也希望能開放自定義的格式（譬如我想要讓檔名為 `作品ID(作品名稱)_上傳時間_首標籤_Page x`）
我不太確定這樣是否算是可供參考的明確需求，總而言之就是可以自由透過參數調整要怎麼安置檔案，畢竟每個人的分類偏好可能都不一樣，檔名的部分同理（目前好像沒看到可以修改檔名的部分？）

**Comment by y-young** [comment]
> Pixiv自選參數進行資料夾分類呢？譬如可以自選分類（漫畫／插圖／動圖）、作品資料（作品名稱、作品ID、作者ID、上傳時間、首標籤、頁數等），然後自己看怎麼分類
> Twitter的話可能就只能透過用戶ID之類的，其他部分不太有研究
> 譬如我能自己選擇用 `Pixiv/Manga(參數調整)/PIXIV_ID(參數調整)` 儲存，檔名也希望能開放自定義的格式（譬如我想要讓檔名為 `作品ID(作品名稱)_上傳時間_首標籤_Page x`）
> 我不太確定這樣是否算是可供參考的明確需求，總而言之就是可以自由透過參數調整要怎麼安置檔案，畢竟每個人的分類偏好可能都不一樣，檔名的部分同理（目前好像沒看到可以修改檔名的部分？）

感谢，很有参考价值。自选参数是最具灵活性的方式，也在考虑范围之内，但缺点是会增加复杂性，比如不同来源的分类方式如何统一？如果不统一的话每个都要配置一遍会不会太麻烦？
顺带一提，Twitter 等网站的用户名是可以更改的，只有 ID 是唯一识别方式，如果根据用户名分类的话会出问题，除非根据 ID 自动合并，但这样又会更麻烦…

**Comment by yotv2000tw** [comment]
> > Pixiv自選參數進行資料夾分類呢？譬如可以自選分類（漫畫／插圖／動圖）、作品資料（作品名稱、作品ID、作者ID、上傳時間、首標籤、頁數等），然後自己看怎麼分類
> > Twitter的話可能就只能透過用戶ID之類的，其他部分不太有研究
> > 譬如我能自己選擇用 `Pixiv/Manga(參數調整)/PIXIV_ID(參數調整)` 儲存，檔名也希望能開放自定義的格式（譬如我想要讓檔名為 `作品ID(作品名稱)_上傳時間_首標籤_Page x`）
> > 我不太確定這樣是否算是可供參考的明確需求，總而言之就是可以自由透過參數調整要怎麼安置檔案，畢竟每個人的分類偏好可能都不一樣，檔名的部分同理（目前好像沒看到可以修改檔名的部分？）
> 
> 感谢，很有参考价值。自选参数是最具灵活性的方式，也在考虑范围之内，但缺点是会增加复杂性，比如不同来源的分类方式如何统一？如果不统一的话每个都要配置一遍会不会太麻烦？ 顺带一提，Twitter 等网站的用户名是可以更改的，只有 ID 是唯一识别方式，如果根据用户名分类的话会出问题，除非根据 ID 自动合并，但这样又会更麻烦…

是可以設定默認分類方式，就不用每個東西都要自己設定一次，自定義只在需要的時候進行（譬如我只想要Pixiv跟Twitter這兩個來源的檔案進行更細部的分類）
不同來源可能要默認不同資料夾，譬如默認Pixiv的檔案都先放置於 `Pixiv/` 之下，至於細部要怎麼分類，可以透過自己調整的方式進行
我個人也認同分類方式無法統一，每個網站能達成的分類細緻程度大不相同，所以真的要達成，恐怕每個來源都必須設置調整方式（代表最多可能需要數個分類方式，無法互相共用），不能只靠單一分類方式來達成
這部分的技術上問題，以及綜合考量複雜程度，我沒辦法想像，因為我對coding沒什麼概念，只能提供拙見，如果有不清楚的部分還請見諒。
