### ISSUE TITLE
cdn.syndication.twimg.com returns 404 page.

### ISSUE THREAD

**Issue by ghosrt** [y-young/nazurin#57]
**Describe the bug**
`cdn.syndication.twimg.com` returns a 404 page now instead of JSON data.

**To Reproduce**
1. Send a tweet link to the bot.
2. Bot will reply with "Tweet not found or unavailable."

**Expected behavior**
Tweet images will be stored and sent to the Telegram channel.

**Error output / Logs**
Since the unexpected output happens on Twitter's side, no error log output from Nazurin.

**Environment (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Python Version: 3.10.7

**Additional context**
Since it should be a problem on Twitter's side, using another data source might be helpful (ex. `nitter.it`).

**Comment by y-young** [comment]
Thanks for your report, this issue should be fixed in the [latest release](https://github.com/y-young/nazurin/releases/tag/v2.2.1), please upgrade and see if the problem persists.

**Comment by ghosrt** [comment]
> Thanks for your report, this issue should be fixed in the [latest release](https://github.com/y-young/nazurin/releases/tag/v2.2.1), please upgrade and see if the problem persists.

Problem solved. Thanks!
